#include <vector>
#include <string>
#include <iostream>
#include <SDL2/SDL.h>
#include "Event.hpp"
#include "IMap.hpp"
#include "IGUI.hpp"
#include "IGfxLib.hpp"
#include "ITile.hpp"
#include "libSDL.hpp"

namespace arcade
{
  std::map<SDL_Keycode, KeyboardKey> libSDL::m_keys =
    {
    {SDLK_0, KB_0},
    {SDLK_1, KB_1},
    {SDLK_2, KB_2},
    {SDLK_3, KB_3},
    {SDLK_4, KB_4},
    {SDLK_5, KB_5},
    {SDLK_6, KB_6},
    {SDLK_7, KB_7},
    {SDLK_8, KB_8},
    {SDLK_9, KB_9},
    {SDLK_RIGHT, KB_ARROW_RIGHT},
    {SDLK_LEFT, KB_ARROW_LEFT},
    {SDLK_UP, KB_ARROW_UP},
    {SDLK_DOWN, KB_ARROW_DOWN},
    {SDLK_SPACE, KB_SPACE},
    {SDLK_RETURN, KB_ENTER},
    {224, KB_0},
    {SDLK_AMPERSAND, KB_1},
    {233, KB_2},
    {34, KB_3},
    {39, KB_4},
    {40, KB_5},
    {45, KB_6},
    {232, KB_7},
    {95, KB_8},
    {231, KB_9},
    {SDLK_ESCAPE, KB_ESCAPE},
    {SDLK_BACKSPACE, KB_BACKSPACE},
    {SDLK_a, KB_A},
    {SDLK_b, KB_B},
    {SDLK_c, KB_C},
    {SDLK_d, KB_D},
    {SDLK_e, KB_E},
    {SDLK_f, KB_F},
    {SDLK_g, KB_G},
    {SDLK_h, KB_H},
    {SDLK_i, KB_I},
    {SDLK_j, KB_J},
    {SDLK_k, KB_K},
    {SDLK_l, KB_L},
    {SDLK_m, KB_M},
    {SDLK_n, KB_N},
    {SDLK_o, KB_O},
    {SDLK_p, KB_P},
    {SDLK_q, KB_Q},
    {SDLK_r, KB_R},
    {SDLK_s, KB_S},
    {SDLK_t, KB_T},
    {SDLK_u, KB_U},
    {SDLK_v, KB_V},
    {SDLK_w, KB_W},
    {SDLK_x, KB_X},
    {SDLK_y, KB_Y},
    {SDLK_z, KB_Z}
    };
}
